name: name-date
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.10
  - cudatoolkit
  - tqdm
  - numpy
  - matplotlib
  - scikit-learn
  - seaborn
  - pip

  - pip:
      - torch
      - torchvision
      - torchinfo
      - requests
